package cli

import (
	"context"
	"fmt"
	"os"
	"time"

	"github.com/spf13/cobra"

	apxv1 "github.com/HuntedRaven7/Archaeopteryx/api/apx/v1"
)

func newApplyConfigCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "apply-config <apxconfig.yaml>",
		Short: "Apply the machine config to a node in maintenance mode",
		Long: `Apply the machine config generated by "apxctl gen config" to an
unconfigured node.

The node must be reachable with its bootstrap admin identity (--ca/--cert/--key
from the node state dir, or run on the node itself) and, when maintained, the
onboarding token shown on the node console/journal:
  apxctl --ca ca.crt --cert admin.crt --key admin.key \
         apply-config apxconfig.yaml --maintenance-token <token>`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			b, err := os.ReadFile(args[0])
			if err != nil {
				return fmt.Errorf("read config: %w", err)
			}

			c, err := newClient()
			if err != nil {
				return err
			}
			defer c.Close()

			ctx, cancel := context.WithTimeout(cmd.Context(), 30*time.Second)
			defer cancel()

			resp, err := c.Machine.ApplyConfig(ctx, &apxv1.ApplyConfigRequest{
				Config:           string(b),
				MaintenanceToken: maintenanceToken,
			})
			if err != nil {
				return fmt.Errorf("apply config: %w", err)
			}
			fmt.Println(resp.Message)
			return nil
		},
	}
	cmd.Flags().StringVar(&maintenanceToken, "maintenance-token", "", "onboarding token printed by the node in maintenance mode")
	return cmd
}

var maintenanceToken string
