// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: apx/v1/apx.proto

package apxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KubernetesStatus_State int32

const (
	KubernetesStatus_STATE_UNSPECIFIED KubernetesStatus_State = 0
	KubernetesStatus_DISABLED          KubernetesStatus_State = 1
	KubernetesStatus_STOPPED           KubernetesStatus_State = 2
	KubernetesStatus_ACTIVATING        KubernetesStatus_State = 3
	KubernetesStatus_ACTIVE            KubernetesStatus_State = 4
	KubernetesStatus_FAILED            KubernetesStatus_State = 5
)

// Enum value maps for KubernetesStatus_State.
var (
	KubernetesStatus_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "DISABLED",
		2: "STOPPED",
		3: "ACTIVATING",
		4: "ACTIVE",
		5: "FAILED",
	}
	KubernetesStatus_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"DISABLED":          1,
		"STOPPED":           2,
		"ACTIVATING":        3,
		"ACTIVE":            4,
		"FAILED":            5,
	}
)

func (x KubernetesStatus_State) Enum() *KubernetesStatus_State {
	p := new(KubernetesStatus_State)
	*p = x
	return p
}

func (x KubernetesStatus_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KubernetesStatus_State) Descriptor() protoreflect.EnumDescriptor {
	return file_apx_v1_apx_proto_enumTypes[0].Descriptor()
}

func (KubernetesStatus_State) Type() protoreflect.EnumType {
	return &file_apx_v1_apx_proto_enumTypes[0]
}

func (x KubernetesStatus_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KubernetesStatus_State.Descriptor instead.
func (KubernetesStatus_State) EnumDescriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{5, 0}
}

type ServiceActionRequest_Action int32

const (
	ServiceActionRequest_ACTION_UNSPECIFIED ServiceActionRequest_Action = 0
	ServiceActionRequest_START              ServiceActionRequest_Action = 1
	ServiceActionRequest_STOP               ServiceActionRequest_Action = 2
	ServiceActionRequest_RESTART            ServiceActionRequest_Action = 3
	ServiceActionRequest_RELOAD             ServiceActionRequest_Action = 4
)

// Enum value maps for ServiceActionRequest_Action.
var (
	ServiceActionRequest_Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "START",
		2: "STOP",
		3: "RESTART",
		4: "RELOAD",
	}
	ServiceActionRequest_Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"START":              1,
		"STOP":               2,
		"RESTART":            3,
		"RELOAD":             4,
	}
)

func (x ServiceActionRequest_Action) Enum() *ServiceActionRequest_Action {
	p := new(ServiceActionRequest_Action)
	*p = x
	return p
}

func (x ServiceActionRequest_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceActionRequest_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_apx_v1_apx_proto_enumTypes[1].Descriptor()
}

func (ServiceActionRequest_Action) Type() protoreflect.EnumType {
	return &file_apx_v1_apx_proto_enumTypes[1]
}

func (x ServiceActionRequest_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceActionRequest_Action.Descriptor instead.
func (ServiceActionRequest_Action) EnumDescriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{15, 0}
}

type RebootRequest_Mode int32

const (
	RebootRequest_MODE_UNSPECIFIED RebootRequest_Mode = 0
	RebootRequest_MODE_GRACEFUL    RebootRequest_Mode = 1
	RebootRequest_MODE_POWEROFF    RebootRequest_Mode = 2
)

// Enum value maps for RebootRequest_Mode.
var (
	RebootRequest_Mode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "MODE_GRACEFUL",
		2: "MODE_POWEROFF",
	}
	RebootRequest_Mode_value = map[string]int32{
		"MODE_UNSPECIFIED": 0,
		"MODE_GRACEFUL":    1,
		"MODE_POWEROFF":    2,
	}
)

func (x RebootRequest_Mode) Enum() *RebootRequest_Mode {
	p := new(RebootRequest_Mode)
	*p = x
	return p
}

func (x RebootRequest_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RebootRequest_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_apx_v1_apx_proto_enumTypes[2].Descriptor()
}

func (RebootRequest_Mode) Type() protoreflect.EnumType {
	return &file_apx_v1_apx_proto_enumTypes[2]
}

func (x RebootRequest_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RebootRequest_Mode.Descriptor instead.
func (RebootRequest_Mode) EnumDescriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{17, 0}
}

type UpdateRequest_Component int32

const (
	UpdateRequest_COMPONENT_UNSPECIFIED UpdateRequest_Component = 0
	UpdateRequest_COMPONENT_ALL         UpdateRequest_Component = 1
	UpdateRequest_COMPONENT_OS          UpdateRequest_Component = 2
	UpdateRequest_COMPONENT_K0S         UpdateRequest_Component = 3
)

// Enum value maps for UpdateRequest_Component.
var (
	UpdateRequest_Component_name = map[int32]string{
		0: "COMPONENT_UNSPECIFIED",
		1: "COMPONENT_ALL",
		2: "COMPONENT_OS",
		3: "COMPONENT_K0S",
	}
	UpdateRequest_Component_value = map[string]int32{
		"COMPONENT_UNSPECIFIED": 0,
		"COMPONENT_ALL":         1,
		"COMPONENT_OS":          2,
		"COMPONENT_K0S":         3,
	}
)

func (x UpdateRequest_Component) Enum() *UpdateRequest_Component {
	p := new(UpdateRequest_Component)
	*p = x
	return p
}

func (x UpdateRequest_Component) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateRequest_Component) Descriptor() protoreflect.EnumDescriptor {
	return file_apx_v1_apx_proto_enumTypes[3].Descriptor()
}

func (UpdateRequest_Component) Type() protoreflect.EnumType {
	return &file_apx_v1_apx_proto_enumTypes[3]
}

func (x UpdateRequest_Component) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateRequest_Component.Descriptor instead.
func (UpdateRequest_Component) EnumDescriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{29, 0}
}

type VersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionRequest) Reset() {
	*x = VersionRequest{}
	mi := &file_apx_v1_apx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRequest) ProtoMessage() {}

func (x *VersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionRequest.ProtoReflect.Descriptor instead.
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{0}
}

type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Commit        string                 `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	BuildDate     string                 `protobuf:"bytes,3,opt,name=build_date,json=buildDate,proto3" json:"build_date,omitempty"`
	GoVersion     string                 `protobuf:"bytes,4,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	Platform      string                 `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_apx_v1_apx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{1}
}

func (x *VersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *VersionResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *VersionResponse) GetBuildDate() string {
	if x != nil {
		return x.BuildDate
	}
	return ""
}

func (x *VersionResponse) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

func (x *VersionResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_apx_v1_apx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{2}
}

type GetStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Hostname       string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	OsId           string                 `protobuf:"bytes,2,opt,name=os_id,json=osId,proto3" json:"os_id,omitempty"`
	OsName         string                 `protobuf:"bytes,3,opt,name=os_name,json=osName,proto3" json:"os_name,omitempty"`
	OsPrettyName   string                 `protobuf:"bytes,4,opt,name=os_pretty_name,json=osPrettyName,proto3" json:"os_pretty_name,omitempty"`
	OsVersion      string                 `protobuf:"bytes,5,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	OsImageVersion string                 `protobuf:"bytes,6,opt,name=os_image_version,json=osImageVersion,proto3" json:"os_image_version,omitempty"`
	KernelRelease  string                 `protobuf:"bytes,7,opt,name=kernel_release,json=kernelRelease,proto3" json:"kernel_release,omitempty"`
	BootId         string                 `protobuf:"bytes,8,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	UptimeSeconds  int64                  `protobuf:"varint,9,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	BootSlot       *SlotInfo              `protobuf:"bytes,10,opt,name=boot_slot,json=bootSlot,proto3" json:"boot_slot,omitempty"`
	Kubernetes     *KubernetesStatus      `protobuf:"bytes,11,opt,name=kubernetes,proto3" json:"kubernetes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_apx_v1_apx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatusResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *GetStatusResponse) GetOsId() string {
	if x != nil {
		return x.OsId
	}
	return ""
}

func (x *GetStatusResponse) GetOsName() string {
	if x != nil {
		return x.OsName
	}
	return ""
}

func (x *GetStatusResponse) GetOsPrettyName() string {
	if x != nil {
		return x.OsPrettyName
	}
	return ""
}

func (x *GetStatusResponse) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *GetStatusResponse) GetOsImageVersion() string {
	if x != nil {
		return x.OsImageVersion
	}
	return ""
}

func (x *GetStatusResponse) GetKernelRelease() string {
	if x != nil {
		return x.KernelRelease
	}
	return ""
}

func (x *GetStatusResponse) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *GetStatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *GetStatusResponse) GetBootSlot() *SlotInfo {
	if x != nil {
		return x.BootSlot
	}
	return nil
}

func (x *GetStatusResponse) GetKubernetes() *KubernetesStatus {
	if x != nil {
		return x.Kubernetes
	}
	return nil
}

type SlotInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Current          string                 `protobuf:"bytes,1,opt,name=current,proto3" json:"current,omitempty"`
	RunningVersion   string                 `protobuf:"bytes,2,opt,name=running_version,json=runningVersion,proto3" json:"running_version,omitempty"`
	InstalledVersion string                 `protobuf:"bytes,3,opt,name=installed_version,json=installedVersion,proto3" json:"installed_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SlotInfo) Reset() {
	*x = SlotInfo{}
	mi := &file_apx_v1_apx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotInfo) ProtoMessage() {}

func (x *SlotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotInfo.ProtoReflect.Descriptor instead.
func (*SlotInfo) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{4}
}

func (x *SlotInfo) GetCurrent() string {
	if x != nil {
		return x.Current
	}
	return ""
}

func (x *SlotInfo) GetRunningVersion() string {
	if x != nil {
		return x.RunningVersion
	}
	return ""
}

func (x *SlotInfo) GetInstalledVersion() string {
	if x != nil {
		return x.InstalledVersion
	}
	return ""
}

type KubernetesStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         KubernetesStatus_State `protobuf:"varint,1,opt,name=state,proto3,enum=apx.v1.KubernetesStatus_State" json:"state,omitempty"`
	SysextMerged  bool                   `protobuf:"varint,2,opt,name=sysext_merged,json=sysextMerged,proto3" json:"sysext_merged,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	NodeName      string                 `protobuf:"bytes,4,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	Ready         bool                   `protobuf:"varint,6,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesStatus) Reset() {
	*x = KubernetesStatus{}
	mi := &file_apx_v1_apx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesStatus) ProtoMessage() {}

func (x *KubernetesStatus) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesStatus.ProtoReflect.Descriptor instead.
func (*KubernetesStatus) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{5}
}

func (x *KubernetesStatus) GetState() KubernetesStatus_State {
	if x != nil {
		return x.State
	}
	return KubernetesStatus_STATE_UNSPECIFIED
}

func (x *KubernetesStatus) GetSysextMerged() bool {
	if x != nil {
		return x.SysextMerged
	}
	return false
}

func (x *KubernetesStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *KubernetesStatus) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *KubernetesStatus) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *KubernetesStatus) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type BootstrapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapRequest) Reset() {
	*x = BootstrapRequest{}
	mi := &file_apx_v1_apx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapRequest) ProtoMessage() {}

func (x *BootstrapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapRequest.ProtoReflect.Descriptor instead.
func (*BootstrapRequest) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{6}
}

type BootstrapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapResponse) Reset() {
	*x = BootstrapResponse{}
	mi := &file_apx_v1_apx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapResponse) ProtoMessage() {}

func (x *BootstrapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapResponse.ProtoReflect.Descriptor instead.
func (*BootstrapResponse) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{7}
}

func (x *BootstrapResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type KubeconfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubeconfigRequest) Reset() {
	*x = KubeconfigRequest{}
	mi := &file_apx_v1_apx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeconfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeconfigRequest) ProtoMessage() {}

func (x *KubeconfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeconfigRequest.ProtoReflect.Descriptor instead.
func (*KubeconfigRequest) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{8}
}

type KubeconfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kubeconfig    []byte                 `protobuf:"bytes,1,opt,name=kubeconfig,proto3" json:"kubeconfig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubeconfigResponse) Reset() {
	*x = KubeconfigResponse{}
	mi := &file_apx_v1_apx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeconfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeconfigResponse) ProtoMessage() {}

func (x *KubeconfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeconfigResponse.ProtoReflect.Descriptor instead.
func (*KubeconfigResponse) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{9}
}

func (x *KubeconfigResponse) GetKubeconfig() []byte {
	if x != nil {
		return x.Kubeconfig
	}
	return nil
}

type LogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unit          string                 `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	Follow        bool                   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`
	TailLines     int32                  `protobuf:"varint,3,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	Since         string                 `protobuf:"bytes,4,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_apx_v1_apx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{10}
}

func (x *LogsRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *LogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *LogsRequest) GetTailLines() int32 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

func (x *LogsRequest) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

type LogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsResponse) Reset() {
	*x = LogsResponse{}
	mi := &file_apx_v1_apx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsResponse) ProtoMessage() {}

func (x *LogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsResponse.ProtoReflect.Descriptor instead.
func (*LogsResponse) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{11}
}

func (x *LogsResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesRequest) Reset() {
	*x = ListServicesRequest{}
	mi := &file_apx_v1_apx_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest) ProtoMessage() {}

func (x *ListServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest.ProtoReflect.Descriptor instead.
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{12}
}

type ServiceInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State           string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	SubState        string                 `protobuf:"bytes,3,opt,name=sub_state,json=subState,proto3" json:"sub_state,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ActiveState     string                 `protobuf:"bytes,5,opt,name=active_state,json=activeState,proto3" json:"active_state,omitempty"`
	ActiveEnterUsec int64                  `protobuf:"varint,6,opt,name=active_enter_usec,json=activeEnterUsec,proto3" json:"active_enter_usec,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_apx_v1_apx_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{13}
}

func (x *ServiceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ServiceInfo) GetSubState() string {
	if x != nil {
		return x.SubState
	}
	return ""
}

func (x *ServiceInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ServiceInfo) GetActiveState() string {
	if x != nil {
		return x.ActiveState
	}
	return ""
}

func (x *ServiceInfo) GetActiveEnterUsec() int64 {
	if x != nil {
		return x.ActiveEnterUsec
	}
	return 0
}

type ListServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceInfo         `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_apx_v1_apx_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{14}
}

func (x *ListServicesResponse) GetServices() []*ServiceInfo {
	if x != nil {
		return x.Services
	}
	return nil
}

type ServiceActionRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Unit          string                      `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	Action        ServiceActionRequest_Action `protobuf:"varint,2,opt,name=action,proto3,enum=apx.v1.ServiceActionRequest_Action" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceActionRequest) Reset() {
	*x = ServiceActionRequest{}
	mi := &file_apx_v1_apx_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceActionRequest) ProtoMessage() {}

func (x *ServiceActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceActionRequest.ProtoReflect.Descriptor instead.
func (*ServiceActionRequest) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{15}
}

func (x *ServiceActionRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *ServiceActionRequest) GetAction() ServiceActionRequest_Action {
	if x != nil {
		return x.Action
	}
	return ServiceActionRequest_ACTION_UNSPECIFIED
}

type ServiceActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceActionResponse) Reset() {
	*x = ServiceActionResponse{}
	mi := &file_apx_v1_apx_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceActionResponse) ProtoMessage() {}

func (x *ServiceActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceActionResponse.ProtoReflect.Descriptor instead.
func (*ServiceActionResponse) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{16}
}

func (x *ServiceActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RebootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          RebootRequest_Mode     `protobuf:"varint,1,opt,name=mode,proto3,enum=apx.v1.RebootRequest_Mode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebootRequest) Reset() {
	*x = RebootRequest{}
	mi := &file_apx_v1_apx_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebootRequest) ProtoMessage() {}

func (x *RebootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebootRequest.ProtoReflect.Descriptor instead.
func (*RebootRequest) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{17}
}

func (x *RebootRequest) GetMode() RebootRequest_Mode {
	if x != nil {
		return x.Mode
	}
	return RebootRequest_MODE_UNSPECIFIED
}

type RebootResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebootResponse) Reset() {
	*x = RebootResponse{}
	mi := &file_apx_v1_apx_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebootResponse) ProtoMessage() {}

func (x *RebootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebootResponse.ProtoReflect.Descriptor instead.
func (*RebootResponse) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{18}
}

func (x *RebootResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_apx_v1_apx_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{19}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_apx_v1_apx_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{20}
}

func (x *ShutdownResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wipe          bool                   `protobuf:"varint,1,opt,name=wipe,proto3" json:"wipe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_apx_v1_apx_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{21}
}

func (x *ResetRequest) GetWipe() bool {
	if x != nil {
		return x.Wipe
	}
	return false
}

type ResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_apx_v1_apx_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{22}
}

func (x *ResetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApplyConfigRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Config           string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Reboot           bool                   `protobuf:"varint,2,opt,name=reboot,proto3" json:"reboot,omitempty"`
	MaintenanceToken string                 `protobuf:"bytes,3,opt,name=maintenance_token,json=maintenanceToken,proto3" json:"maintenance_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ApplyConfigRequest) Reset() {
	*x = ApplyConfigRequest{}
	mi := &file_apx_v1_apx_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyConfigRequest) ProtoMessage() {}

func (x *ApplyConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyConfigRequest.ProtoReflect.Descriptor instead.
func (*ApplyConfigRequest) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{23}
}

func (x *ApplyConfigRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *ApplyConfigRequest) GetReboot() bool {
	if x != nil {
		return x.Reboot
	}
	return false
}

func (x *ApplyConfigRequest) GetMaintenanceToken() string {
	if x != nil {
		return x.MaintenanceToken
	}
	return ""
}

type ApplyConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyConfigResponse) Reset() {
	*x = ApplyConfigResponse{}
	mi := &file_apx_v1_apx_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyConfigResponse) ProtoMessage() {}

func (x *ApplyConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyConfigResponse.ProtoReflect.Descriptor instead.
func (*ApplyConfigResponse) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{24}
}

func (x *ApplyConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_apx_v1_apx_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{25}
}

type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_apx_v1_apx_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{26}
}

func (x *GetConfigResponse) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type GenerateClientConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Endpoints     []string               `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Ca            string                 `protobuf:"bytes,3,opt,name=ca,proto3" json:"ca,omitempty"`
	Crt           string                 `protobuf:"bytes,4,opt,name=crt,proto3" json:"crt,omitempty"`
	Key           string                 `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	Ttl           string                 `protobuf:"bytes,6,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Organization  string                 `protobuf:"bytes,7,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateClientConfigRequest) Reset() {
	*x = GenerateClientConfigRequest{}
	mi := &file_apx_v1_apx_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateClientConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateClientConfigRequest) ProtoMessage() {}

func (x *GenerateClientConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateClientConfigRequest.ProtoReflect.Descriptor instead.
func (*GenerateClientConfigRequest) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{27}
}

func (x *GenerateClientConfigRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GenerateClientConfigRequest) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *GenerateClientConfigRequest) GetCa() string {
	if x != nil {
		return x.Ca
	}
	return ""
}

func (x *GenerateClientConfigRequest) GetCrt() string {
	if x != nil {
		return x.Crt
	}
	return ""
}

func (x *GenerateClientConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GenerateClientConfigRequest) GetTtl() string {
	if x != nil {
		return x.Ttl
	}
	return ""
}

func (x *GenerateClientConfigRequest) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

type GenerateClientConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ca            string                 `protobuf:"bytes,1,opt,name=ca,proto3" json:"ca,omitempty"`
	Crt           string                 `protobuf:"bytes,2,opt,name=crt,proto3" json:"crt,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Config        string                 `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateClientConfigResponse) Reset() {
	*x = GenerateClientConfigResponse{}
	mi := &file_apx_v1_apx_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateClientConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateClientConfigResponse) ProtoMessage() {}

func (x *GenerateClientConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateClientConfigResponse.ProtoReflect.Descriptor instead.
func (*GenerateClientConfigResponse) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{28}
}

func (x *GenerateClientConfigResponse) GetCa() string {
	if x != nil {
		return x.Ca
	}
	return ""
}

func (x *GenerateClientConfigResponse) GetCrt() string {
	if x != nil {
		return x.Crt
	}
	return ""
}

func (x *GenerateClientConfigResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GenerateClientConfigResponse) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type UpdateRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Component     UpdateRequest_Component `protobuf:"varint,1,opt,name=component,proto3,enum=apx.v1.UpdateRequest_Component" json:"component,omitempty"`
	CheckOnly     bool                    `protobuf:"varint,2,opt,name=check_only,json=checkOnly,proto3" json:"check_only,omitempty"`
	StageOnly     bool                    `protobuf:"varint,3,opt,name=stage_only,json=stageOnly,proto3" json:"stage_only,omitempty"`
	Reboot        bool                    `protobuf:"varint,4,opt,name=reboot,proto3" json:"reboot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_apx_v1_apx_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateRequest) GetComponent() UpdateRequest_Component {
	if x != nil {
		return x.Component
	}
	return UpdateRequest_COMPONENT_UNSPECIFIED
}

func (x *UpdateRequest) GetCheckOnly() bool {
	if x != nil {
		return x.CheckOnly
	}
	return false
}

func (x *UpdateRequest) GetStageOnly() bool {
	if x != nil {
		return x.StageOnly
	}
	return false
}

func (x *UpdateRequest) GetReboot() bool {
	if x != nil {
		return x.Reboot
	}
	return false
}

type UpdatePlan struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Components     []*UpdateComponent     `protobuf:"bytes,1,rep,name=components,proto3" json:"components,omitempty"`
	RebootRequired bool                   `protobuf:"varint,2,opt,name=reboot_required,json=rebootRequired,proto3" json:"reboot_required,omitempty"`
	RebootOwed     bool                   `protobuf:"varint,3,opt,name=reboot_owed,json=rebootOwed,proto3" json:"reboot_owed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdatePlan) Reset() {
	*x = UpdatePlan{}
	mi := &file_apx_v1_apx_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlan) ProtoMessage() {}

func (x *UpdatePlan) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlan.ProtoReflect.Descriptor instead.
func (*UpdatePlan) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{30}
}

func (x *UpdatePlan) GetComponents() []*UpdateComponent {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *UpdatePlan) GetRebootRequired() bool {
	if x != nil {
		return x.RebootRequired
	}
	return false
}

func (x *UpdatePlan) GetRebootOwed() bool {
	if x != nil {
		return x.RebootOwed
	}
	return false
}

type UpdateComponent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CurrentVersion  string                 `protobuf:"bytes,3,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	LatestVersion   string                 `protobuf:"bytes,4,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	UpdateAvailable bool                   `protobuf:"varint,5,opt,name=update_available,json=updateAvailable,proto3" json:"update_available,omitempty"`
	RebootRequired  bool                   `protobuf:"varint,6,opt,name=reboot_required,json=rebootRequired,proto3" json:"reboot_required,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Message         string                 `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateComponent) Reset() {
	*x = UpdateComponent{}
	mi := &file_apx_v1_apx_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateComponent) ProtoMessage() {}

func (x *UpdateComponent) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateComponent.ProtoReflect.Descriptor instead.
func (*UpdateComponent) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{31}
}

func (x *UpdateComponent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateComponent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateComponent) GetCurrentVersion() string {
	if x != nil {
		return x.CurrentVersion
	}
	return ""
}

func (x *UpdateComponent) GetLatestVersion() string {
	if x != nil {
		return x.LatestVersion
	}
	return ""
}

func (x *UpdateComponent) GetUpdateAvailable() bool {
	if x != nil {
		return x.UpdateAvailable
	}
	return false
}

func (x *UpdateComponent) GetRebootRequired() bool {
	if x != nil {
		return x.RebootRequired
	}
	return false
}

func (x *UpdateComponent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateComponent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*UpdateResponse_Plan
	//	*UpdateResponse_Progress
	//	*UpdateResponse_Error
	Payload       isUpdateResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_apx_v1_apx_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{32}
}

func (x *UpdateResponse) GetPayload() isUpdateResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UpdateResponse) GetPlan() *UpdatePlan {
	if x != nil {
		if x, ok := x.Payload.(*UpdateResponse_Plan); ok {
			return x.Plan
		}
	}
	return nil
}

func (x *UpdateResponse) GetProgress() string {
	if x != nil {
		if x, ok := x.Payload.(*UpdateResponse_Progress); ok {
			return x.Progress
		}
	}
	return ""
}

func (x *UpdateResponse) GetError() string {
	if x != nil {
		if x, ok := x.Payload.(*UpdateResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isUpdateResponse_Payload interface {
	isUpdateResponse_Payload()
}

type UpdateResponse_Plan struct {
	Plan *UpdatePlan `protobuf:"bytes,1,opt,name=plan,proto3,oneof"`
}

type UpdateResponse_Progress struct {
	Progress string `protobuf:"bytes,2,opt,name=progress,proto3,oneof"`
}

type UpdateResponse_Error struct {
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*UpdateResponse_Plan) isUpdateResponse_Payload() {}

func (*UpdateResponse_Progress) isUpdateResponse_Payload() {}

func (*UpdateResponse_Error) isUpdateResponse_Payload() {}

type RollbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reboot        bool                   `protobuf:"varint,1,opt,name=reboot,proto3" json:"reboot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackRequest) Reset() {
	*x = RollbackRequest{}
	mi := &file_apx_v1_apx_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackRequest) ProtoMessage() {}

func (x *RollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackRequest.ProtoReflect.Descriptor instead.
func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{33}
}

func (x *RollbackRequest) GetReboot() bool {
	if x != nil {
		return x.Reboot
	}
	return false
}

type RollbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackResponse) Reset() {
	*x = RollbackResponse{}
	mi := &file_apx_v1_apx_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackResponse) ProtoMessage() {}

func (x *RollbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackResponse.ProtoReflect.Descriptor instead.
func (*RollbackResponse) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{34}
}

func (x *RollbackResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsRequest) Reset() {
	*x = EventsRequest{}
	mi := &file_apx_v1_apx_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsRequest) ProtoMessage() {}

func (x *EventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsRequest.ProtoReflect.Descriptor instead.
func (*EventsRequest) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{35}
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TimestampNs   int64                  `protobuf:"varint,2,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_apx_v1_apx_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_apx_v1_apx_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_apx_v1_apx_proto_rawDescGZIP(), []int{36}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Event) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_apx_v1_apx_proto protoreflect.FileDescriptor

const file_apx_v1_apx_proto_rawDesc = "" +
	"\n" +
	"\x10apx/v1/apx.proto\x12\x06apx.v1\"\x10\n" +
	"\x0eVersionRequest\"\x9d\x01\n" +
	"\x0fVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\tR\x06commit\x12\x1d\n" +
	"\n" +
	"build_date\x18\x03 \x01(\tR\tbuildDate\x12\x1d\n" +
	"\n" +
	"go_version\x18\x04 \x01(\tR\tgoVersion\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\tR\bplatform\"\x12\n" +
	"\x10GetStatusRequest\"\x9c\x03\n" +
	"\x11GetStatusResponse\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x13\n" +
	"\x05os_id\x18\x02 \x01(\tR\x04osId\x12\x17\n" +
	"\aos_name\x18\x03 \x01(\tR\x06osName\x12$\n" +
	"\x0eos_pretty_name\x18\x04 \x01(\tR\fosPrettyName\x12\x1d\n" +
	"\n" +
	"os_version\x18\x05 \x01(\tR\tosVersion\x12(\n" +
	"\x10os_image_version\x18\x06 \x01(\tR\x0eosImageVersion\x12%\n" +
	"\x0ekernel_release\x18\a \x01(\tR\rkernelRelease\x12\x17\n" +
	"\aboot_id\x18\b \x01(\tR\x06bootId\x12%\n" +
	"\x0euptime_seconds\x18\t \x01(\x03R\ruptimeSeconds\x12-\n" +
	"\tboot_slot\x18\n" +
	" \x01(\v2\x10.apx.v1.SlotInfoR\bbootSlot\x128\n" +
	"\n" +
	"kubernetes\x18\v \x01(\v2\x18.apx.v1.KubernetesStatusR\n" +
	"kubernetes\"z\n" +
	"\bSlotInfo\x12\x18\n" +
	"\acurrent\x18\x01 \x01(\tR\acurrent\x12'\n" +
	"\x0frunning_version\x18\x02 \x01(\tR\x0erunningVersion\x12+\n" +
	"\x11installed_version\x18\x03 \x01(\tR\x10installedVersion\"\xb1\x02\n" +
	"\x10KubernetesStatus\x124\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1e.apx.v1.KubernetesStatus.StateR\x05state\x12#\n" +
	"\rsysext_merged\x18\x02 \x01(\bR\fsysextMerged\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1b\n" +
	"\tnode_name\x18\x04 \x01(\tR\bnodeName\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x14\n" +
	"\x05ready\x18\x06 \x01(\bR\x05ready\"a\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bDISABLED\x10\x01\x12\v\n" +
	"\aSTOPPED\x10\x02\x12\x0e\n" +
	"\n" +
	"ACTIVATING\x10\x03\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x04\x12\n" +
	"\n" +
	"\x06FAILED\x10\x05\"\x12\n" +
	"\x10BootstrapRequest\"-\n" +
	"\x11BootstrapResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x13\n" +
	"\x11KubeconfigRequest\"4\n" +
	"\x12KubeconfigResponse\x12\x1e\n" +
	"\n" +
	"kubeconfig\x18\x01 \x01(\fR\n" +
	"kubeconfig\"n\n" +
	"\vLogsRequest\x12\x12\n" +
	"\x04unit\x18\x01 \x01(\tR\x04unit\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x03 \x01(\x05R\ttailLines\x12\x14\n" +
	"\x05since\x18\x04 \x01(\tR\x05since\"\"\n" +
	"\fLogsResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x15\n" +
	"\x13ListServicesRequest\"\xc5\x01\n" +
	"\vServiceInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1b\n" +
	"\tsub_state\x18\x03 \x01(\tR\bsubState\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12!\n" +
	"\factive_state\x18\x05 \x01(\tR\vactiveState\x12*\n" +
	"\x11active_enter_usec\x18\x06 \x01(\x03R\x0factiveEnterUsec\"G\n" +
	"\x14ListServicesResponse\x12/\n" +
	"\bservices\x18\x01 \x03(\v2\x13.apx.v1.ServiceInfoR\bservices\"\xb7\x01\n" +
	"\x14ServiceActionRequest\x12\x12\n" +
	"\x04unit\x18\x01 \x01(\tR\x04unit\x12;\n" +
	"\x06action\x18\x02 \x01(\x0e2#.apx.v1.ServiceActionRequest.ActionR\x06action\"N\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05START\x10\x01\x12\b\n" +
	"\x04STOP\x10\x02\x12\v\n" +
	"\aRESTART\x10\x03\x12\n" +
	"\n" +
	"\x06RELOAD\x10\x04\"1\n" +
	"\x15ServiceActionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x83\x01\n" +
	"\rRebootRequest\x12.\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x1a.apx.v1.RebootRequest.ModeR\x04mode\"B\n" +
	"\x04Mode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rMODE_GRACEFUL\x10\x01\x12\x11\n" +
	"\rMODE_POWEROFF\x10\x02\"*\n" +
	"\x0eRebootResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x11\n" +
	"\x0fShutdownRequest\",\n" +
	"\x10ShutdownResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\"\n" +
	"\fResetRequest\x12\x12\n" +
	"\x04wipe\x18\x01 \x01(\bR\x04wipe\")\n" +
	"\rResetResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"q\n" +
	"\x12ApplyConfigRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\x12\x16\n" +
	"\x06reboot\x18\x02 \x01(\bR\x06reboot\x12+\n" +
	"\x11maintenance_token\x18\x03 \x01(\tR\x10maintenanceToken\"/\n" +
	"\x13ApplyConfigResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x12\n" +
	"\x10GetConfigRequest\"+\n" +
	"\x11GetConfigResponse\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\"\xb9\x01\n" +
	"\x1bGenerateClientConfigRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tendpoints\x18\x02 \x03(\tR\tendpoints\x12\x0e\n" +
	"\x02ca\x18\x03 \x01(\tR\x02ca\x12\x10\n" +
	"\x03crt\x18\x04 \x01(\tR\x03crt\x12\x10\n" +
	"\x03key\x18\x05 \x01(\tR\x03key\x12\x10\n" +
	"\x03ttl\x18\x06 \x01(\tR\x03ttl\x12\"\n" +
	"\forganization\x18\a \x01(\tR\forganization\"j\n" +
	"\x1cGenerateClientConfigResponse\x12\x0e\n" +
	"\x02ca\x18\x01 \x01(\tR\x02ca\x12\x10\n" +
	"\x03crt\x18\x02 \x01(\tR\x03crt\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x16\n" +
	"\x06config\x18\x04 \x01(\tR\x06config\"\x84\x02\n" +
	"\rUpdateRequest\x12=\n" +
	"\tcomponent\x18\x01 \x01(\x0e2\x1f.apx.v1.UpdateRequest.ComponentR\tcomponent\x12\x1d\n" +
	"\n" +
	"check_only\x18\x02 \x01(\bR\tcheckOnly\x12\x1d\n" +
	"\n" +
	"stage_only\x18\x03 \x01(\bR\tstageOnly\x12\x16\n" +
	"\x06reboot\x18\x04 \x01(\bR\x06reboot\"^\n" +
	"\tComponent\x12\x19\n" +
	"\x15COMPONENT_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rCOMPONENT_ALL\x10\x01\x12\x10\n" +
	"\fCOMPONENT_OS\x10\x02\x12\x11\n" +
	"\rCOMPONENT_K0S\x10\x03\"\x8f\x01\n" +
	"\n" +
	"UpdatePlan\x127\n" +
	"\n" +
	"components\x18\x01 \x03(\v2\x17.apx.v1.UpdateComponentR\n" +
	"components\x12'\n" +
	"\x0freboot_required\x18\x02 \x01(\bR\x0erebootRequired\x12\x1f\n" +
	"\vreboot_owed\x18\x03 \x01(\bR\n" +
	"rebootOwed\"\x91\x02\n" +
	"\x0fUpdateComponent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12'\n" +
	"\x0fcurrent_version\x18\x03 \x01(\tR\x0ecurrentVersion\x12%\n" +
	"\x0elatest_version\x18\x04 \x01(\tR\rlatestVersion\x12)\n" +
	"\x10update_available\x18\x05 \x01(\bR\x0fupdateAvailable\x12'\n" +
	"\x0freboot_required\x18\x06 \x01(\bR\x0erebootRequired\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessage\"{\n" +
	"\x0eUpdateResponse\x12(\n" +
	"\x04plan\x18\x01 \x01(\v2\x12.apx.v1.UpdatePlanH\x00R\x04plan\x12\x1c\n" +
	"\bprogress\x18\x02 \x01(\tH\x00R\bprogress\x12\x16\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05errorB\t\n" +
	"\apayload\")\n" +
	"\x0fRollbackRequest\x12\x16\n" +
	"\x06reboot\x18\x01 \x01(\bR\x06reboot\",\n" +
	"\x10RollbackResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x0f\n" +
	"\rEventsRequest\"\xde\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\ftimestamp_ns\x18\x02 \x01(\x03R\vtimestampNs\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x127\n" +
	"\bmetadata\x18\x05 \x03(\v2\x1b.apx.v1.Event.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xaa\b\n" +
	"\x0eMachineService\x12:\n" +
	"\aVersion\x12\x16.apx.v1.VersionRequest\x1a\x17.apx.v1.VersionResponse\x12@\n" +
	"\tGetStatus\x12\x18.apx.v1.GetStatusRequest\x1a\x19.apx.v1.GetStatusResponse\x12@\n" +
	"\tBootstrap\x12\x18.apx.v1.BootstrapRequest\x1a\x19.apx.v1.BootstrapResponse\x12C\n" +
	"\n" +
	"Kubeconfig\x12\x19.apx.v1.KubeconfigRequest\x1a\x1a.apx.v1.KubeconfigResponse\x123\n" +
	"\x04Logs\x12\x13.apx.v1.LogsRequest\x1a\x14.apx.v1.LogsResponse0\x01\x12I\n" +
	"\fListServices\x12\x1b.apx.v1.ListServicesRequest\x1a\x1c.apx.v1.ListServicesResponse\x12L\n" +
	"\rServiceAction\x12\x1c.apx.v1.ServiceActionRequest\x1a\x1d.apx.v1.ServiceActionResponse\x127\n" +
	"\x06Reboot\x12\x15.apx.v1.RebootRequest\x1a\x16.apx.v1.RebootResponse\x12=\n" +
	"\bShutdown\x12\x17.apx.v1.ShutdownRequest\x1a\x18.apx.v1.ShutdownResponse\x124\n" +
	"\x05Reset\x12\x14.apx.v1.ResetRequest\x1a\x15.apx.v1.ResetResponse\x12F\n" +
	"\vApplyConfig\x12\x1a.apx.v1.ApplyConfigRequest\x1a\x1b.apx.v1.ApplyConfigResponse\x12@\n" +
	"\tGetConfig\x12\x18.apx.v1.GetConfigRequest\x1a\x19.apx.v1.GetConfigResponse\x12a\n" +
	"\x14GenerateClientConfig\x12#.apx.v1.GenerateClientConfigRequest\x1a$.apx.v1.GenerateClientConfigResponse\x129\n" +
	"\x06Update\x12\x15.apx.v1.UpdateRequest\x1a\x16.apx.v1.UpdateResponse0\x01\x12=\n" +
	"\bRollback\x12\x17.apx.v1.RollbackRequest\x1a\x18.apx.v1.RollbackResponse\x120\n" +
	"\x06Events\x12\x15.apx.v1.EventsRequest\x1a\r.apx.v1.Event0\x01B8Z6github.com/HuntedRaven7/Archaeopteryx/api/apx/v1;apxv1b\x06proto3"

var (
	file_apx_v1_apx_proto_rawDescOnce sync.Once
	file_apx_v1_apx_proto_rawDescData []byte
)

func file_apx_v1_apx_proto_rawDescGZIP() []byte {
	file_apx_v1_apx_proto_rawDescOnce.Do(func() {
		file_apx_v1_apx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apx_v1_apx_proto_rawDesc), len(file_apx_v1_apx_proto_rawDesc)))
	})
	return file_apx_v1_apx_proto_rawDescData
}

var file_apx_v1_apx_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_apx_v1_apx_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_apx_v1_apx_proto_goTypes = []any{
	(KubernetesStatus_State)(0),          // 0: apx.v1.KubernetesStatus.State
	(ServiceActionRequest_Action)(0),     // 1: apx.v1.ServiceActionRequest.Action
	(RebootRequest_Mode)(0),              // 2: apx.v1.RebootRequest.Mode
	(UpdateRequest_Component)(0),         // 3: apx.v1.UpdateRequest.Component
	(*VersionRequest)(nil),               // 4: apx.v1.VersionRequest
	(*VersionResponse)(nil),              // 5: apx.v1.VersionResponse
	(*GetStatusRequest)(nil),             // 6: apx.v1.GetStatusRequest
	(*GetStatusResponse)(nil),            // 7: apx.v1.GetStatusResponse
	(*SlotInfo)(nil),                     // 8: apx.v1.SlotInfo
	(*KubernetesStatus)(nil),             // 9: apx.v1.KubernetesStatus
	(*BootstrapRequest)(nil),             // 10: apx.v1.BootstrapRequest
	(*BootstrapResponse)(nil),            // 11: apx.v1.BootstrapResponse
	(*KubeconfigRequest)(nil),            // 12: apx.v1.KubeconfigRequest
	(*KubeconfigResponse)(nil),           // 13: apx.v1.KubeconfigResponse
	(*LogsRequest)(nil),                  // 14: apx.v1.LogsRequest
	(*LogsResponse)(nil),                 // 15: apx.v1.LogsResponse
	(*ListServicesRequest)(nil),          // 16: apx.v1.ListServicesRequest
	(*ServiceInfo)(nil),                  // 17: apx.v1.ServiceInfo
	(*ListServicesResponse)(nil),         // 18: apx.v1.ListServicesResponse
	(*ServiceActionRequest)(nil),         // 19: apx.v1.ServiceActionRequest
	(*ServiceActionResponse)(nil),        // 20: apx.v1.ServiceActionResponse
	(*RebootRequest)(nil),                // 21: apx.v1.RebootRequest
	(*RebootResponse)(nil),               // 22: apx.v1.RebootResponse
	(*ShutdownRequest)(nil),              // 23: apx.v1.ShutdownRequest
	(*ShutdownResponse)(nil),             // 24: apx.v1.ShutdownResponse
	(*ResetRequest)(nil),                 // 25: apx.v1.ResetRequest
	(*ResetResponse)(nil),                // 26: apx.v1.ResetResponse
	(*ApplyConfigRequest)(nil),           // 27: apx.v1.ApplyConfigRequest
	(*ApplyConfigResponse)(nil),          // 28: apx.v1.ApplyConfigResponse
	(*GetConfigRequest)(nil),             // 29: apx.v1.GetConfigRequest
	(*GetConfigResponse)(nil),            // 30: apx.v1.GetConfigResponse
	(*GenerateClientConfigRequest)(nil),  // 31: apx.v1.GenerateClientConfigRequest
	(*GenerateClientConfigResponse)(nil), // 32: apx.v1.GenerateClientConfigResponse
	(*UpdateRequest)(nil),                // 33: apx.v1.UpdateRequest
	(*UpdatePlan)(nil),                   // 34: apx.v1.UpdatePlan
	(*UpdateComponent)(nil),              // 35: apx.v1.UpdateComponent
	(*UpdateResponse)(nil),               // 36: apx.v1.UpdateResponse
	(*RollbackRequest)(nil),              // 37: apx.v1.RollbackRequest
	(*RollbackResponse)(nil),             // 38: apx.v1.RollbackResponse
	(*EventsRequest)(nil),                // 39: apx.v1.EventsRequest
	(*Event)(nil),                        // 40: apx.v1.Event
	nil,                                  // 41: apx.v1.Event.MetadataEntry
}
var file_apx_v1_apx_proto_depIdxs = []int32{
	8,  // 0: apx.v1.GetStatusResponse.boot_slot:type_name -> apx.v1.SlotInfo
	9,  // 1: apx.v1.GetStatusResponse.kubernetes:type_name -> apx.v1.KubernetesStatus
	0,  // 2: apx.v1.KubernetesStatus.state:type_name -> apx.v1.KubernetesStatus.State
	17, // 3: apx.v1.ListServicesResponse.services:type_name -> apx.v1.ServiceInfo
	1,  // 4: apx.v1.ServiceActionRequest.action:type_name -> apx.v1.ServiceActionRequest.Action
	2,  // 5: apx.v1.RebootRequest.mode:type_name -> apx.v1.RebootRequest.Mode
	3,  // 6: apx.v1.UpdateRequest.component:type_name -> apx.v1.UpdateRequest.Component
	35, // 7: apx.v1.UpdatePlan.components:type_name -> apx.v1.UpdateComponent
	34, // 8: apx.v1.UpdateResponse.plan:type_name -> apx.v1.UpdatePlan
	41, // 9: apx.v1.Event.metadata:type_name -> apx.v1.Event.MetadataEntry
	4,  // 10: apx.v1.MachineService.Version:input_type -> apx.v1.VersionRequest
	6,  // 11: apx.v1.MachineService.GetStatus:input_type -> apx.v1.GetStatusRequest
	10, // 12: apx.v1.MachineService.Bootstrap:input_type -> apx.v1.BootstrapRequest
	12, // 13: apx.v1.MachineService.Kubeconfig:input_type -> apx.v1.KubeconfigRequest
	14, // 14: apx.v1.MachineService.Logs:input_type -> apx.v1.LogsRequest
	16, // 15: apx.v1.MachineService.ListServices:input_type -> apx.v1.ListServicesRequest
	19, // 16: apx.v1.MachineService.ServiceAction:input_type -> apx.v1.ServiceActionRequest
	21, // 17: apx.v1.MachineService.Reboot:input_type -> apx.v1.RebootRequest
	23, // 18: apx.v1.MachineService.Shutdown:input_type -> apx.v1.ShutdownRequest
	25, // 19: apx.v1.MachineService.Reset:input_type -> apx.v1.ResetRequest
	27, // 20: apx.v1.MachineService.ApplyConfig:input_type -> apx.v1.ApplyConfigRequest
	29, // 21: apx.v1.MachineService.GetConfig:input_type -> apx.v1.GetConfigRequest
	31, // 22: apx.v1.MachineService.GenerateClientConfig:input_type -> apx.v1.GenerateClientConfigRequest
	33, // 23: apx.v1.MachineService.Update:input_type -> apx.v1.UpdateRequest
	37, // 24: apx.v1.MachineService.Rollback:input_type -> apx.v1.RollbackRequest
	39, // 25: apx.v1.MachineService.Events:input_type -> apx.v1.EventsRequest
	5,  // 26: apx.v1.MachineService.Version:output_type -> apx.v1.VersionResponse
	7,  // 27: apx.v1.MachineService.GetStatus:output_type -> apx.v1.GetStatusResponse
	11, // 28: apx.v1.MachineService.Bootstrap:output_type -> apx.v1.BootstrapResponse
	13, // 29: apx.v1.MachineService.Kubeconfig:output_type -> apx.v1.KubeconfigResponse
	15, // 30: apx.v1.MachineService.Logs:output_type -> apx.v1.LogsResponse
	18, // 31: apx.v1.MachineService.ListServices:output_type -> apx.v1.ListServicesResponse
	20, // 32: apx.v1.MachineService.ServiceAction:output_type -> apx.v1.ServiceActionResponse
	22, // 33: apx.v1.MachineService.Reboot:output_type -> apx.v1.RebootResponse
	24, // 34: apx.v1.MachineService.Shutdown:output_type -> apx.v1.ShutdownResponse
	26, // 35: apx.v1.MachineService.Reset:output_type -> apx.v1.ResetResponse
	28, // 36: apx.v1.MachineService.ApplyConfig:output_type -> apx.v1.ApplyConfigResponse
	30, // 37: apx.v1.MachineService.GetConfig:output_type -> apx.v1.GetConfigResponse
	32, // 38: apx.v1.MachineService.GenerateClientConfig:output_type -> apx.v1.GenerateClientConfigResponse
	36, // 39: apx.v1.MachineService.Update:output_type -> apx.v1.UpdateResponse
	38, // 40: apx.v1.MachineService.Rollback:output_type -> apx.v1.RollbackResponse
	40, // 41: apx.v1.MachineService.Events:output_type -> apx.v1.Event
	26, // [26:42] is the sub-list for method output_type
	10, // [10:26] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_apx_v1_apx_proto_init() }
func file_apx_v1_apx_proto_init() {
	if File_apx_v1_apx_proto != nil {
		return
	}
	file_apx_v1_apx_proto_msgTypes[32].OneofWrappers = []any{
		(*UpdateResponse_Plan)(nil),
		(*UpdateResponse_Progress)(nil),
		(*UpdateResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apx_v1_apx_proto_rawDesc), len(file_apx_v1_apx_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apx_v1_apx_proto_goTypes,
		DependencyIndexes: file_apx_v1_apx_proto_depIdxs,
		EnumInfos:         file_apx_v1_apx_proto_enumTypes,
		MessageInfos:      file_apx_v1_apx_proto_msgTypes,
	}.Build()
	File_apx_v1_apx_proto = out.File
	file_apx_v1_apx_proto_goTypes = nil
	file_apx_v1_apx_proto_depIdxs = nil
}
